version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 5001
    command: npm start
    volumes:
      - .:/usr/src/app/
      - /app/node_modules
    ports:
      - 5002:5001
    depends_on:
    - mongodb
    environment:
      DEBUG: 'true'
    networks:
      testing_net:
        ipv4_address: 142.28.1.1

  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      testing_net:
        ipv4_address: 142.28.2.1

volumes:
  db_data: {}
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 142.28.0.0/16